name: flutter_pusher
description: A flutter plugin for the Pusher library.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ninjasolutions.flutter_pusher
    pluginClass: FlutterPusherPlugin
